version: "3"

services:
  app:
    container_name: app-laraapi
    build: ./docker/php
    environment:
      APP_ENV: "development"
      APP_DEBUG: "true"
      LOG_CHANNEL: "stderr"
      DB_CONNECTION: "pgsql"
      DB_HOST: "db"
      DB_PORT: "5433"
      DB_DATABASE: "docker"
      DB_USERNAME: "docker"
      DB_PASSWORD: "docker"
    volumes:
      - ./server:/var/www
    expose:
      - 9000
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nginx-laraapi
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app

  db:
    image: postgres:12
    container_name: db-laraapi
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
